#pragma once

#define PLAY_FIELD_HEIGHT_2 20.0f 
#define PLAY_FIELD_WIDTH_2 10.0f
#define BOUNDARY_FIELD_HEIGHT_2 25.0f
#define BOUNDARY_FIELD_WIDTH_2 12.5f
#define ENEMY_SPAWN_X_MIN -9.0f
#define ENEMY_SPAWN_X_MAX 9.0f
#define WINDOW_WIDTH 400
#define WINDOW_HEIGHT 800