#pragma once

#define PLAYER_ID 0U
#define ENEMY_PLANE_ID 1U
#define PLAYER_BULLET_ID 2U
#define ENEMY_BULLET_ID 3U
#define ENEMY_BOAT_ID 4U
#define ENEMY_TURRET_ID 5U

#define EXPLOSION_ID 100U
#define PLAYER_EXPLOSION_ID 101U
#define PLAYER_BULLET_EXPLOSION_ID 102U
#define ENEMY_PLANE_EXPLOSION_ID 103U
#define ENEMY_BULLET_EXPLOSION_ID 104U

#define OTHER_ID 999U