#pragma once

enum OBJECT_ID {
	PLAYER = 0U,
	ENEMY_PLANE = 1U,
	PLAYER_BULLET = 2U,
	ENEMY_BULLET = 3U,
	ENEMY_BOAT = 4U,
	ENEMY_TURRET = 5U,

	EXPLOSION = 100U,
	PLAYER_EXPLOSION = 101U,
	PLAYER_BULLET_EXPLOSION = 102U,
	ENEMY_PLANE_EXPLOSION = 103U,
	ENEMY_BULLET_EXPLOSION = 104U,

	OTHER = 999U
};